### ISSUE TITLE
Questions about UVC data

### ISSUE THREAD

**Issue by jpwrobinson** [jpwrobinson/grazing-gradients#1]
Space for UVC queries for Nick...

**Comment by Jeneen** [comment]
- [ ] No dates for Chagos

- [ ] No lat long values for sites

**Comment by jpwrobinson** [comment]
#### Seychelles

- [ ] Seychelles surveys used a fixed species list. Was this also done in other regions?
- [ ] Some Seychelles species changed names from 1994-2017. Any herbivores??

**Comment by JanDajka** [comment]
- [x] Why are abundances/500m^2 in Maldives either 2 or 5? Are the fish weird?

**Comment by jpwrobinson** [comment]
**General questions**

- [ ] Fishing gradients - what happens in Maldives?
- [ ] What is exposed/sheltered (i.e. Chagos + Maldives) vs. patch/carbonate/granite (Seychelles)
