### ISSUE TITLE
Task 4

### ISSUE THREAD

**Issue by Jeneen** [jpwrobinson/grazing-gradients#10]
Methods papers: 
Graham et al. 2014 Plos One = GBR 
Nash et al. 2016 Ecosphere = Seychelles
Darling et al. 2017 Coral Reefs = ALL DATASETS

- [x] Everyone: Write up a brief description of survey methods for each site. Jeneen = Seychelles, James = Maldives, Chagos, Jan = GBR. Put into new Rmd file.

- [x] GROUP modelling of benthos and biomass. Friday.

**Comment by jpwrobinson** [comment]
@JanDajka @Jeneen @samanthajh 

Y'all want to revisit our modelling session next Monday? I GOT GERMAN TREATS. 

(I won't say what they are in case Jan says they're shit)

Welcome back Sam!

**Comment by Jeneen** [comment]
Nom Nom. Im game.

**Comment by JanDajka** [comment]
Welcome back Sam!

I'm game, gotta be via Skype though, I'll be in ze Germany eating shit treats myself. 

Let me know when!

Jay-Bird

**Comment by samanthajh** [comment]
Cheers James! Looking forward to getting stuck in again.... and I love a
good küchen :)

On 10 Jul 2018 1:53 pm, "James Robinson" <notifications@github.com> wrote:

@JanDajka <https://github.com/JanDajka> @Jeneen <https://github.com/Jeneen>
@samanthajh <https://github.com/samanthajh>

Y'all want to revisit our modelling session next Monday? I GOT GERMAN
TREATS.

(I won't say what they are in case Jan says they're shit)

Welcome back Sam!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jpwrobinson/grazing-gradients/issues/10#issuecomment-403811281>,
or mute the thread

**Comment by JanDajka** [comment]
Brownie points for ze Ümlaut.

**Comment by jpwrobinson** [comment]
I can reveal...it is not a küchen

LEC - LEC III B45 has been booked for you, from 15:30 to 16:30 on Monday, 16/07/2018.

(they had no morning times)

**Comment by Jeneen** [comment]
Eek I’ve got a skype at 16:00, any other rooms for the morning?

**Comment by samanthajh** [comment]
Danke schön 😊

**Comment by jpwrobinson** [comment]
Nope nothing that day. How about Tuesday 10am B44?

**Comment by Jeneen** [comment]
Works for me

Sent from Mail for Windows 10

**Comment by JanDajka** [comment]
Yip.

**Comment by samanthajh** [comment]
Affirmative

**Comment by JanDajka** [comment]
Yooo, can I Skype in with anyone?

**Comment by Jeneen** [comment]
Yo, where did we decide we were writing up the methods for each country?

**Comment by jpwrobinson** [comment]
Is that...a....word document? Nooooo!

Stick em in [here](https://github.com/jpwrobinson/grazing-gradients/blob/master/writing/methods/methods-summaries.Rmd)

**Comment by Jeneen** [comment]
merely temporary. we're all good. 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: James Robinson <notifications@github.com> Date: 26/07/2018  17:24  (GMT+00:00) To: jpwrobinson/grazing-gradients <grazing-gradients@noreply.github.com> Cc: Jeneen <jeneenhh@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [jpwrobinson/grazing-gradients] Task 4 (#10) 
Is that...a....word document? Nooooo!
Stick em in here

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jpwrobinson/grazing-gradients","title":"jpwrobinson/grazing-gradients","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/jpwrobinson/grazing-gradients"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jpwrobinson in #10: Is that...a....word document? Nooooo!\r\n\r\nStick em in [here](https://github.com/jpwrobinson/grazing-gradients/blob/master/writing/methods/methods-summaries.Rmd)"}],"action":{"name":"View Issue","url":"https://github.com/jpwrobinson/grazing-gradients/issues/10#issuecomment-408154858"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jpwrobinson/grazing-gradients/issues/10#issuecomment-408154858",
"url": "https://github.com/jpwrobinson/grazing-gradients/issues/10#issuecomment-408154858",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [jpwrobinson/grazing-gradients] Task 4 (#10)",
"sections": [
{
"text": "",
"activityTitle": "**James Robinson**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@jpwrobinson",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"jpwrobinson/grazing-gradients\",\n\"issueId\": 10,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"jpwrobinson/grazing-gradients\",\n\"issueId\": 10\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/jpwrobinson/grazing-gradients/issues/10#issuecomment-408154858"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 352477294\n}"
}
],
"themeColor": "26292E"
}
]
