### ISSUE TITLE
Task 5

### ISSUE THREAD

**Issue by Jeneen** [jpwrobinson/grazing-gradients#11]
JAN/JENEEN/SAM
-  [ ] Complete models for every functional group and every variable, hard coral done

James
- [x] Change management covariate 
- [x] Bite rate cleaning and predictive models

**Comment by jpwrobinson** [comment]
Just remembered that the macroalgae*complexity interaction will need some extra care, because you'll have to plot the change in biomass across both gradients at the same time.

I think the management covariate stuff is already good to go right? I'll add bite rate cleaning for me instead.

**Comment by Jeneen** [comment]
@JanDajka @samanthajh want to get together at some point next week to go over the models? I've done a bit on it (simply copying james code!), just want to make sure it's right and maybe finish it off

**Comment by JanDajka** [comment]
Absolutely, I'm good to go all week!

**Comment by samanthajh** [comment]
Sure thing! :)

**Comment by Jeneen** [comment]
Tuesday at 10?

**Comment by samanthajh** [comment]
Sounds good

**Comment by JanDajka** [comment]
Jaaaaa!

**Comment by samanthajh** [comment]
it's in the old diary ;)

**Comment by JanDajka** [comment]
Bäm.

**Comment by JanDajka** [comment]
Coding attempt this week again?

**Comment by samanthajh** [comment]
Potentially...Weds or Thurs mornings....

**Comment by JanDajka** [comment]
Wednesday then, Thursday is packed. 
10:00?

**Comment by samanthajh** [comment]
Works for me 😊

**Comment by JanDajka** [comment]
Jeneenie-beanie?

**Comment by Jeneen** [comment]
Can we do a bit earlier, 9/9:30? I’ve got an appointment in town at 11:30.

**Comment by JanDajka** [comment]
Apsaulutely. Everyone okay with 09:00?

**Comment by samanthajh** [comment]
Sure thing chicken wing

**Comment by JanDajka** [comment]
Excellent, I requested to book a room - LEC3 doesn't show up in my booking system.

**Comment by jpwrobinson** [comment]
How are things going everyone!? I'm BACK (almost). Models converging? Residuals normalizing? Fish grazing?

**Comment by JanDajka** [comment]
Ehhm, let's say the challenges increase our learning experience. :-/

**Comment by JanDajka** [comment]
Room A51 booked for tomorrow 09:00 - 11:00.

**Comment by Jeneen** [comment]
kapow

**Comment by JanDajka** [comment]
Dead Man's Bones - Pa Pa Power

https://www.youtube.com/watch?v=FA0zncJOx0E

**Comment by Jeneen** [comment]
James, when do you get back in?

**Comment by jpwrobinson** [comment]
Today! on campus tomorrow. I have cookies from Canada whenever you guys want to meet.

**Comment by Jeneen** [comment]
There are some issues with this (although cookies are appreciated), welcome back... we are basically all not here for 2 months... erm.

We are trying to make a to-do list (we don’t know how to do the model stuff – we are trying, but they don’t really show any strong patterns with the model we have) to get an idea of the timeline for this project, so things aren’t all up in the air while we are all away.

We put it up as a new issue on git!

Peace and love

**Comment by samanthajh** [comment]
So, did we arrange to meet tomorrow.....?

**Comment by Jeneen** [comment]
Can do anything before lunch!

**Comment by JanDajka** [comment]
Can only do 11:30 until 12:30 then.

**Comment by samanthajh** [comment]
Sounds good to me....

**Comment by jpwrobinson** [comment]
works for me too!
