### ISSUE TITLE
Confidence intervals for GLMERS

### ISSUE THREAD

**Issue by jpwrobinson** [jpwrobinson/grazing-gradients#21]
lme4 doesn't do prediction confidence intervals by default because standard errors ignore random effect uncertainty, and so the package authors are unwilling to provide functions that might do this automatically.

However, there are other alternatives of representing uncertainty (and showing some uncertainty is always better than not showing any). lme4 authors do support using bootMer to represent uncertainty, so I propose we follow this tutorial to create bootstrapped intervals on Figures 2 and 3:

https://rpubs.com/hughes/84484

- [ ] Add CI intervals to Figure 2
- [ ] Add CI intervals to Figure 3

**Comment by JanDajka** [comment]
Sorry that I still haven't attacked this - couldn't find enough time for it. I'll try my best to get it done on Friday.

**Comment by jpwrobinson** [comment]
No rush. We have an idea of the CIs because of the effect sizes anyway, so will just need this before we submit.

Found this, might help: http://www.remkoduursma.com/post/2017-06-15-bootpredictlme4/

**Comment by JanDajka** [comment]
That somehow looks more approachable than the first link. :-D

**Comment by Jeneen** [comment]
It works for the browsers and scrapers, but not grazers. I'll try again when Jan gets back.

**Comment by JanDajka** [comment]
Mondaaaay!

**Comment by jpwrobinson** [comment]
Got a new analysis going folks, no worries on the intervals!
