### ISSUE TITLE
Figure 1

### ISSUE THREAD

**Issue by jpwrobinson** [jpwrobinson/grazing-gradients#24]
I wondered about a map that showed:

* study sites
* herbivore FG structure
* benthic variation

It would be pretty complicated. Recent paper from Roff et al. (2018, now in our mendeley lib) for inspiration:

![screen shot 2018-11-14 at 09 52 14](https://user-images.githubusercontent.com/5231402/48474749-1f1f1500-e7f3-11e8-9aee-0527bb920e5b.png)

Also open to alternative ideas for Fig 1. Map can also go into supplement.

**Comment by jpwrobinson** [comment]
1) Regions + sites
2) Colours = biomass
3) PCA of benthos

**Comment by JamieMcDevittIrwin** [comment]
Notes on how we did the PCA and K-means clustering:
https://uc-r.github.io/kmeans_clustering#optimal

Used the elbow method to pick the best K (i.e. number of clusters).
