### ISSUE TITLE
What species overlap between regions? What data exists for these species in literature?

### ISSUE THREAD

**Issue by samanthajh** [jpwrobinson/grazing-gradients#3]

**Comment by samanthajh** [comment]
Hi guys,
Check out the paper by Bonaldo (2014) that I added to the Mendeley folder if you haven't read it, it summarises feeding rate studies from around the world by species with bite rates etc.

**Comment by jpwrobinson** [comment]
Keeping bite rate information [here](https://github.com/jpwrobinson/grazing-gradients/commit/fd67607d6cd6b17d45d5800fad3941a3d335587f)
