### ISSUE TITLE
Just checking what we should do by tomorrow's meeting...

### ISSUE THREAD

**Issue by Jeneen** [jpwrobinson/grazing-gradients#5]
Basically, other than determine what questions to ask Nick, I've just looked at 3 gradients and done some basic data structure exploration. Will add some graphs based on what you did too James (looking at site level descriptives). Anything else I'm missing? Don't know if markdown has worked properly, but I've attempted to copy script over.

**Comment by jpwrobinson** [comment]
Looks good to me, merged into my copy no problem. 

Would be good to check which species we have bite rate data on...but we could do that together in the meeting. I'm just going to have a quick scan now.
