### ISSUE TITLE
Tasks for next week

### ISSUE THREAD

**Issue by Jeneen** [jpwrobinson/grazing-gradients#6]
Jeneen
- [x] work out how marshal paper calculated the organic carbon biomass
- [x] clean up r markdown script

James

- [x] clean up names

- [x] prepare spreadsheet [HERE!](https://github.com/jpwrobinson/grazing-gradients/blob/bce5d0e01442acd89a8aaedea916b2ead2613f17/data/herb_biterate_estimates.xlsx)

- [x] do half bejerano paper values

Jan

- [x] other half of bejerano paper

- [x] r markdown scheisse

- [x] BRING COOKIES

**Comment by Jeneen** [comment]
erm I tried to clean up r markdown script and check to see if all the extra jazz didnt appear in the pdf file, but in the process of trying to publish the pdf doc it appeared that i didnt have a load of add ons that are needed. Anyway a few extra files (eg. the TEX) document were produced in the process. Feel free to delete. But question, James, is publishing the pdf doc easy? Have I just tried to do it a stupid way (through knitting)? Either way, it didnt work...

**Comment by Jeneen** [comment]
OOooo never mind, it works now!

**Comment by Jeneen** [comment]
Marshell paper methods for calculating carbon intake:

Bite size for each species and size class was estimated by using a general relationship between carbon (C, organic biomass) intake (g C day−1), and fish body mass (W=Wet body mass in grammes) for herbivorous fish daily consumption (Table S1; g C intake day−1= 0.0342 ×W^0.816; Van Rooij et al., 1998). The Van Rooij et al. (1998) gen- eral relationship between fish body mass (n=13 species from various families and regions) and daily carbon intake is highly correlated (r2= 94.6%), and intuitive, in that bigger fish take bigger bites. As standardised surgeonfish grazer/detritivore species- and size-specific bite size data is not available, it was considered that this general relationship was the best standardised method available to obtain a wide- range of bite size estimates. To convert the daily total carbon intake to the amount taken per bite, the estimated total carbon intake per day was divided by the average daily total bites taken by each species (Marshell, unpublished Heron Island data, and Polunin et al., 1995). Species-specific length–weight relationships were used to calculate thewet biomass (g) of different size classes (Kulbicki et al., 2005).

From cited paper (High biomass and production but low energy transfer efficiency of Caribbean parrotfish: implications for trophicmodels of coral reefs., Van Rooij, 1998)

- (daily C intake=0·0342 xW^0·816; wet body mass W in g) with high correlation (r^2=94·6%, n=13)

**Comment by jpwrobinson** [comment]
Let's talk about TEX stuff today. Looks like git pull is still working ok but it is a pain to have all those extra files coming in after knitting the Rmd.

**Comment by jpwrobinson** [comment]
Bejarano paper methods for bite rates:

* Feeding frequency surveys using 5 cameras per site, set in afternoons to film 1 patch of 1m^2. 
* Feeding frequency = bites per hour per m^2. 
* Fishes >5cm in total length
* Reported frequencies are site-level means across 5 camera replicates

We are missing bite *sizes*.

**Comment by JanDajka** [comment]
Are we doing anything with the species that aren't in the UVC-data but for which we have bite rates available? (e.g. Siganus punctatisimus, Scarus quoyi)

**Comment by jpwrobinson** [comment]
I think we can ignore them for now. Could be something to draw on if we want to generate family-level averages later, but may be extra work that we can leave aside for now.
