### ISSUE TITLE
Tasks for next week 2

### ISSUE THREAD

**Issue by jpwrobinson** [jpwrobinson/grazing-gradients#7]
**Je-Ninety-Nine**

- [x] Get average biomass per FG per transect into master Rdata

- [ ] Examine biomass patterns

**Yaaaannnn**

- [ ] Examine biomass patterns

- [ ] Get us a colour blind palette (www.colorbrewer2.org)

- [x] Add GBR to Rmarkdown

**James**

- [x] Get benthic data cleaned

- [x] Figure out gitignore problem

**Comment by Jeneen** [comment]
@jpwrobinson not sure if the mean that I've calculated makes sense (or at least I'm not sure what your suggestion was in that email you've sent round)... I've used "herb" dataset to get a mean biomass for each FG in each country-site-transect, pooled over the years. Not sure how we want to deal with different lengthed transects? And until we get dates for Chagos, not sure if we want to split up the survey years (like we said before, into pre-bleached and post-bleached).

**Comment by jpwrobinson** [comment]
That sounds great. What do you mean by pooled over years? If it's at the transect level average, then there will be multiple transects per year or date..right?

Different length transects is ok for biomass estimates - the biomass column is kg per hectare, so corrects for transect length. But we may want to think about including transect area as an offset term in a linear model , but let's leave that aside for now.

And yeah, we need dates for Chagos. I think we'll want to split up years/dates and account for that in the models. Definitely want to take advantage of changing benthic condition through time somehow (e.g bleaching).

**Comment by Jeneen** [comment]
Yup, just saying I havent split the years up into pre-post bleaching for transect averages! Interestingly grazer biomass per transect is really not that high in Chagos, it's pretty much level with the seychelles.
So, the basic graph that I just put up is basically biomass for each FG in each country with replicates (used to calculate SE bars) being sites x transects for each country.

**Comment by Jeneen** [comment]
Nick has hit me up with chagos dates
woop woop

**Comment by jpwrobinson** [comment]
excelllent. want to push up and I can add into benthic dataframe?

**Comment by Jeneen** [comment]
I've added the chagos dates to wio_gbr_herb_master.Rdata and wio_herb_benthic.Rdata... think you might have changed something between my pull-push... so hopefully it's not gone weird.
