### ISSUE TITLE
Tasks 3

### ISSUE THREAD

**Issue by Jeneen** [jpwrobinson/grazing-gradients#9]
- [x] make sure all functional grouping match up across regions
@jpwrobinson the only mismatch between datasets is Siganus argenteus which is listed as a grazer rather than a browzer in GBR

- [x] fix chagos site names

- [x] benthic cleaning todo list

**^^ this all needs Nick's input**

**Comment by Jeneen** [comment]
I haven't come across anything on functional groups of fish across climate graidents! could be a really interesting avenue James! seen the paper "Projecting global marine biodiversity impacts under climate
change scenarios"... a couple figures there that look like what you drew out, would be cool to do a sort of MaxEnt style map as well

**Comment by jpwrobinson** [comment]
That paper is EXACTLY the motivation for this. Cheung's current postdoc (Gabriel Reygondeau) has a Nature paper coming out in a few days that shows this with a new biodiversity dataset, which would have herbivore/reef fish presence/absence at a 5km scale across the tropics. His dataset is publicly available in a year, so they can write as many papers as possible in that time, but we chatted at the conf. last week and he could be keen to share.

Also this: http://depts.washington.edu/oldenlab/wordpress/wp-content/uploads/2017/09/Nature_ClimateChange_2017.pdf

The most recent / only analysis of fish vulnerability to climate changes. Comte used published lab expts. to estimate physiological tolerances, which I imagine are few and far between for reef fish. Cheung defined thermal sensitivity according to their observed ranges, which can be done with a simple presence/absence biodiversity dataset.

**Comment by Jeneen** [comment]
So @JanDajka  was able to just have a look at biomass of FG across benthic gradients, it doesn't really tell us much... but as soon as all the unique id names are updated (are they? @jpwrobinson ), we can average across transects within countries and use those as points, rather than just whacking in all the points and hopefully some SICK patterns will emerge.

**Comment by jpwrobinson** [comment]
interesting the raw data doesn't produce much - guessing there is a lot of noise. The unique id names should allow you to average biomass estimates at the site level: although the ID types vary by region (Seychelles with dates), each identifies a unique site in space and time. For example:

Seychelles = year.site habitat       e.g. 2011.Mahe W Patch
Chagos = reef.site              e.g. Great Chagos Bank.Eagle (S2)
Maldives = site.reef               e.g. Maarehaa.Huvadhoo
GBR = site.reef                        e.g. Rib1.Rib

This gives us 132 sites, each composed of 4 to 16 replicate UVCs (point counts in Seychelles, transects elsewhere, of varying lengths).

WHICH IS SICK

**Comment by JanDajka** [comment]
That sounds awesome, good work!
Can't seem to find the figure on FG across benthic gradient you mentioned in your commits, @Jeneen . 

Shall we meet soon?

**Comment by jpwrobinson** [comment]
Yup! Tomorrow anytime or Wednesday before 11 works for me.

**Comment by JanDajka** [comment]
Both work for me.

**Comment by Jeneen** [comment]
Tomorrow morn then?? How does 10 sound?

**Comment by JanDajka** [comment]
Bäm! Done.

**Comment by jpwrobinson** [comment]
Let's do it. I got coffee and cookies!

⁣Sent from BlueMail ​
